
// 更新角色数据
export const UPDATE_WIKI_CHARACTER = 'UPDATE_WIKI_CHARACTER'
// 更新角色列表数据
export const UPDATE_WIKI_CHARACTER_LIST = 'UPDATE_WIKI_CHARACTER_LIST'

// 更新地点数据
export const UPDATE_WIKI_LOCATION = 'UPDATE_WIKI_LOCATION'
// 更新地点列表数据
export const UPDATE_WIKI_LOCATION_LIST = 'UPDATE_WIKI_LOCATION_LIST'

// 更新剧集数据
export const UPDATE_WIKI_EPISODE = 'UPDATE_WIKI_EPISODE'
// 更新剧集列表数据
export const UPDATE_WIKI_EPISODE_LIST = 'UPDATE_WIKI_EPISODE_LIST'
